volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_django_media: {}

services:
  django: &django
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: backend_production_django
    volumes:
      - production_django_media:/app/backend/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: backend_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    ports:
      - "100.86.58.86:63001:5432"

  redis:
    restart: unless-stopped
    image: redis:6

  celeryworker:
    restart: unless-stopped
    <<: *django
    image: backend_production_celeryworker
    command: /start-celeryworker
    #deploy:
    #replicas: 2

  celerybeat:
    restart: unless-stopped
    <<: *django
    image: backend_production_celerybeat
    command: /start-celerybeat

  flower:
    restart: unless-stopped
    <<: *django
    image: backend_production_flower
    command: /start-flower

  awscli:
    build:
      context: .
      dockerfile: ./compose/production/aws/Dockerfile
    image: backend_production_awscli
    env_file:
      - ./.envs/.production/.django
    volumes:
      - production_postgres_data_backups:/backups:z

  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: backend_local_nginx
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
    ports:
      - 100.86.58.86:63000:80
