# Generated by Django 4.2.16 on 2025-03-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waifu", "0004_alter_telegramuser_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="blur_data_url",
            field=models.TextField(blank=True, default=""),
        ),
    ]
