# Generated by Django 4.2.21 on 2026-08-07 09:26

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ("waifu", "0005_image_blur_data_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="embedding",
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
