# Generated by Django 4.2.21 on 2026-08-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waifu", "0006_image_embedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("openrouter_base_url", models.URLField(default="https://openrouter.ai", max_length=5000)),
                ("embedding_model", models.CharField(default="google/gemini-embedding-2", max_length=255)),
                ("embedding_api_key", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
