# Generated by Django 4.2.21 on 2026-04-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rent_ai", "0002_product_productcategory_producttag_productimage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="data_source_url",
            field=models.URLField(blank=True, max_length=5000),
        ),
    ]
