# Generated by Django 4.2.21 on 2026-04-08

from django.db import migrations
from pgvector.django import VectorExtension
import pgvector.django.vector


class Migration(migrations.Migration):
    dependencies = [
        ("rent_ai", "0003_alter_setting_data_source_url"),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name="product",
            name="embedding",
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
