# Generated by Django 4.2.21 on 2025-08-06 15:06

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = [
        ("cinematch", "0001_initial"),
    ]

    operations = [VectorExtension()]
