# Generated by Django 4.2.21 on 2025-08-06 15:21

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ("cinematch", "0002_pgvector"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="embedding",
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
