# Generated by Django 4.2.21 on 2025-05-24 13:36

from django.db import migrations, models
import nz_store.utils


class Migration(migrations.Migration):

    dependencies = [
        ("nz_store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=nz_store.utils.get_product_image_upload_path),
        ),
    ]
