# Generated by Django 4.2.21 on 2025-05-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nz_store", "0004_historicalaccountstock"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduct",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
