# Generated by Django 4.2.21 on 2025-05-24 17:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import nz_store.utils
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nz_store", "0005_historicalproduct_is_active_product_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bot_token", models.CharField(blank=True, max_length=255, null=True)),
                ("bot_name", models.CharField(blank=True, max_length=255, null=True)),
                ("bot_description", models.TextField(blank=True, null=True)),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="image",
            field=models.TextField(
                blank=True,
                help_text="Product image (max 5MB, jpg/jpeg/png/webp only)",
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=["jpg", "jpeg", "png", "webp"])
                ],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Product image (max 5MB, jpg/jpeg/png/webp only)",
                null=True,
                upload_to=nz_store.utils.get_product_image_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=["jpg", "jpeg", "png", "webp"])
                ],
            ),
        ),
        migrations.CreateModel(
            name="HistoricalSettings",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("bot_token", models.CharField(blank=True, max_length=255, null=True)),
                ("bot_name", models.CharField(blank=True, max_length=255, null=True)),
                ("bot_description", models.TextField(blank=True, null=True)),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical settings",
                "verbose_name_plural": "historical settingss",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
