# Generated by Django 4.2.21 on 2025-05-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nz_store", "0006_settings_alter_historicalproduct_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalsettings",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Settings",
                "verbose_name_plural": "historical Settings",
            },
        ),
        migrations.AlterModelOptions(
            name="settings",
            options={"verbose_name": "Settings", "verbose_name_plural": "Settings"},
        ),
    ]
