# Generated by Django 4.2.21 on 2025-05-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nz_store", "0007_alter_historicalsettings_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproduct",
            name="stock",
            field=models.PositiveIntegerField(default=0, help_text="Number of available accounts for this product"),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=0, help_text="Number of available accounts for this product"),
        ),
    ]
