# Generated by Django 4.2.21 on 2026-02-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nz_store", "0008_alter_historicalproduct_stock_alter_product_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountstock",
            name="product",
        ),
        migrations.RemoveField(
            model_name="historicalaccountstock",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalaccountstock",
            name="product",
        ),
        migrations.RemoveField(
            model_name="historicalproduct",
            name="category",
        ),
        migrations.RemoveField(
            model_name="historicalproduct",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalsettings",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="order",
            name="account_stock",
        ),
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.RemoveField(
            model_name="order",
            name="telegram_user",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.DeleteModel(
            name="Settings",
        ),
        migrations.DeleteModel(
            name="AccountStock",
        ),
        migrations.DeleteModel(
            name="HistoricalAccountStock",
        ),
        migrations.DeleteModel(
            name="HistoricalProduct",
        ),
        migrations.DeleteModel(
            name="HistoricalSettings",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="ProductCategory",
        ),
        migrations.DeleteModel(
            name="TelegramUser",
        ),
    ]
