#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput

exec /usr/local/bin/gunicorn config.asgi --bind 0.0.0.0:5000 --timeout 120 --workers 5 --chdir=/app -k uvicorn_worker.UvicornWorker
