# Generated by Django 4.2.16 on 2025-02-16 06:28

from django.db import migrations, models
import django.db.models.deletion
import instagram.mixins
import instagram.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoastingLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.CharField(default=uuid.uuid4, editable=False, max_length=36)),
                ("username", models.CharField(max_length=255)),
                ("user_data", models.JSONField()),
                ("roasting_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.CharField(default=uuid.uuid4, editable=False, max_length=36)),
                ("instagram_id", models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("full_name", models.CharField(blank=True, max_length=150)),
                (
                    "profile_picture",
                    models.FileField(
                        blank=True, null=True, upload_to=instagram.utils.user_profile_picture_upload_location
                    ),
                ),
                (
                    "profile_picture_url",
                    models.URLField(help_text="The original profile picture URL from Instagram", max_length=500),
                ),
                ("biography", models.TextField(blank=True)),
                ("follower_count", models.PositiveIntegerField(default=0)),
                ("following_count", models.PositiveIntegerField(default=0)),
                (
                    "updated_from_api_datetime",
                    models.DateTimeField(blank=True, null=True, verbose_name="Update from API datetime"),
                ),
                ("allow_auto_update_stories", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserFollowing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("instagram_id", models.CharField(blank=True, max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("profile_picture_url", models.URLField(max_length=1000)),
                (
                    "profile_picture",
                    models.FileField(
                        blank=True, null=True, upload_to=instagram.utils.user_following_profile_picture_upload_location
                    ),
                ),
                ("is_private_account", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="following", to="instagram.user"
                    ),
                ),
            ],
            bases=(models.Model, instagram.mixins.URLToFileFieldMixin),
        ),
        migrations.CreateModel(
            name="UserFollower",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("instagram_id", models.CharField(blank=True, max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("profile_picture_url", models.URLField(max_length=1000)),
                (
                    "profile_picture",
                    models.FileField(
                        blank=True, null=True, upload_to=instagram.utils.user_follower_profile_picture_upload_location
                    ),
                ),
                ("is_private_account", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="follower", to="instagram.user"
                    ),
                ),
            ],
            bases=(models.Model, instagram.mixins.URLToFileFieldMixin),
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                ("story_id", models.CharField(max_length=50, primary_key=True, serialize=False)),
                ("thumbnail_url", models.URLField(max_length=1000)),
                ("media_url", models.URLField(blank=True, max_length=1000)),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to=instagram.utils.user_stories_upload_location),
                ),
                (
                    "media",
                    models.FileField(blank=True, null=True, upload_to=instagram.utils.user_stories_upload_location),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("story_created_at", models.DateTimeField()),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="instagram.user")),
            ],
            options={
                "verbose_name": "Story",
                "verbose_name_plural": "Stories",
            },
        ),
    ]
