# Generated by Django 4.2.16 on 2025-05-12 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0013_historicaluser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicaluser",
            old_name="updated_from_api_datetime",
            new_name="updated_at_from_api",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="updated_from_api_datetime",
            new_name="updated_at_from_api",
        ),
    ]
