# Generated by Django 4.2.16 on 2025-05-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0014_remove_historicaluser_updated_from_api_datetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluser",
            name="profile_picture_url",
            field=models.URLField(help_text="The original profile picture URL from Instagram", max_length=2500),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture_url",
            field=models.URLField(help_text="The original profile picture URL from Instagram", max_length=2500),
        ),
    ]
