# Generated by Django 4.2.16 on 2025-05-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0015_alter_historicaluser_profile_picture_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="media_url",
            field=models.URLField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name="story",
            name="thumbnail_url",
            field=models.URLField(max_length=2500),
        ),
    ]
