# Generated by Django 4.2.21 on 2025-05-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0016_alter_story_media_url_alter_story_thumbnail_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="allow_auto_update_profile",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="allow_auto_update_profile",
            field=models.BooleanField(default=False),
        ),
    ]
