# Generated by Django 4.2.21 on 2025-08-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0017_historicaluser_allow_auto_update_profile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="auto_update_followers_limit",
            field=models.PositiveIntegerField(default=5, help_text="Free users can update followers up to this limit"),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="auto_update_stories_limit",
            field=models.PositiveIntegerField(default=5, help_text="Free users can update stories up to this limit"),
        ),
        migrations.AddField(
            model_name="user",
            name="auto_update_followers_limit",
            field=models.PositiveIntegerField(default=5, help_text="Free users can update followers up to this limit"),
        ),
        migrations.AddField(
            model_name="user",
            name="auto_update_stories_limit",
            field=models.PositiveIntegerField(default=5, help_text="Free users can update stories up to this limit"),
        ),
    ]
