# Generated by Django 4.2.21 on 2025-08-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0018_historicaluser_auto_update_followers_limit_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicaluser",
            old_name="auto_update_stories_limit",
            new_name="auto_update_stories_limit_count",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="auto_update_stories_limit",
            new_name="auto_update_stories_limit_count",
        ),
        migrations.RemoveField(
            model_name="historicaluser",
            name="auto_update_followers_limit",
        ),
        migrations.RemoveField(
            model_name="user",
            name="auto_update_followers_limit",
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="auto_update_profile_limit_count",
            field=models.PositiveIntegerField(default=5, help_text="Free users can update profile up to this limit"),
        ),
        migrations.AddField(
            model_name="user",
            name="auto_update_profile_limit_count",
            field=models.PositiveIntegerField(default=5, help_text="Free users can update profile up to this limit"),
        ),
    ]
