# Generated by Django 4.2.21 on 2025-12-29 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0019_rename_auto_update_stories_limit_historicaluser_auto_update_stories_limit_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaluser",
            name="history_user",
        ),
        migrations.DeleteModel(
            name="RoastingLog",
        ),
        migrations.RemoveField(
            model_name="story",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userfollower",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userfollowing",
            name="user",
        ),
        migrations.DeleteModel(
            name="HistoricalUser",
        ),
        migrations.DeleteModel(
            name="Story",
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.DeleteModel(
            name="UserFollower",
        ),
        migrations.DeleteModel(
            name="UserFollowing",
        ),
    ]
