name: Deployment

on:
  release:
    types: [published]

jobs:
  Deploying:
    runs-on: ubuntu-latest
    steps:
      - name: Executing Remote SSH Commands Using Password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME}}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            cd ${{ secrets.PATH }}
            git reset --hard
            git pull origin master --force
            echo "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}" > .env
            echo "CSRF_TRUSTED_ORIGINS=${{ secrets.CSRF_TRUSTED_ORIGINS }}" >> .env
            echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
            echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> .env
            echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
            echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env
            echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env
            docker compose -f docker-compose.prod.yaml up --build -d