# Generated by Django 4.2.16 on 2025-02-15 12:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExternalLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=255)),
                ("is_web_app", models.BooleanField(default=False)),
                ("counter", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("webhook_url", models.URLField(blank=True)),
                ("is_maintenance", models.BooleanField(default=False)),
                ("secret_token", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Twitter Downloader Settings",
            },
        ),
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.CharField(max_length=25, unique=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(blank=True, default="", max_length=255)),
                ("username", models.CharField(blank=True, default="", max_length=255)),
                ("is_active", models.BooleanField(default=False)),
                ("is_banned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DownloadedTweet",
            fields=[
                (
                    "uuid",
                    models.CharField(
                        default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False
                    ),
                ),
                ("tweet_url", models.URLField(max_length=500)),
                ("tweet_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "telegram_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="twitter_downloader.telegramuser"
                    ),
                ),
            ],
        ),
    ]
