# Generated by Django 4.2.16 on 2025-02-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter_downloader", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadedtweet",
            name="tweet_data",
            field=models.TextField(default=dict),
        ),
    ]
