# Generated by Django 4.2.21 on 2026-02-08 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("twitter_downloader", "0018_settings_secret_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="BroadcastMessage",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("message", models.TextField(help_text="Pesan yang akan dikirim ke semua user")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sending", "Sending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "total_users",
                    models.PositiveIntegerField(default=0, help_text="Total user yang akan menerima broadcast"),
                ),
                ("sent_count", models.PositiveIntegerField(default=0, help_text="Jumlah pesan yang berhasil dikirim")),
                ("failed_count", models.PositiveIntegerField(default=0, help_text="Jumlah pesan yang gagal dikirim")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, help_text="Waktu mulai broadcasting", null=True)),
                ("completed_at", models.DateTimeField(blank=True, help_text="Waktu selesai broadcasting", null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User yang membuat broadcast ini",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Broadcast Message",
                "verbose_name_plural": "Broadcast Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BroadcastLog",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("success", "Success"), ("failed", "Failed")], max_length=20)),
                ("error_message", models.TextField(blank=True, help_text="Error message jika pengiriman gagal")),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="twitter_downloader.broadcastmessage",
                    ),
                ),
                (
                    "telegram_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="twitter_downloader.telegramuser"
                    ),
                ),
            ],
            options={
                "verbose_name": "Broadcast Log",
                "verbose_name_plural": "Broadcast Logs",
                "ordering": ["-sent_at"],
                "unique_together": {("broadcast", "telegram_user")},
            },
        ),
    ]
