# Generated by Django 4.2.21 on 2026-02-08 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("twitter_downloader", "0019_broadcastmessage_broadcastlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcastlog",
            name="error_message",
            field=models.TextField(blank=True, help_text="Error message if delivery failed"),
        ),
        migrations.AlterField(
            model_name="broadcastmessage",
            name="completed_at",
            field=models.DateTimeField(blank=True, help_text="Broadcasting completion time", null=True),
        ),
        migrations.AlterField(
            model_name="broadcastmessage",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this broadcast",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="broadcastmessage",
            name="failed_count",
            field=models.PositiveIntegerField(default=0, help_text="Number of messages that failed to send"),
        ),
        migrations.AlterField(
            model_name="broadcastmessage",
            name="message",
            field=models.TextField(help_text="Message to be sent to all users"),
        ),
        migrations.AlterField(
            model_name="broadcastmessage",
            name="sent_count",
            field=models.PositiveIntegerField(default=0, help_text="Number of messages successfully sent"),
        ),
        migrations.AlterField(
            model_name="broadcastmessage",
            name="started_at",
            field=models.DateTimeField(blank=True, help_text="Broadcasting start time", null=True),
        ),
        migrations.AlterField(
            model_name="broadcastmessage",
            name="total_users",
            field=models.PositiveIntegerField(default=0, help_text="Total users who will receive the broadcast"),
        ),
    ]
