# Generated by Django 4.2.21 on 2026-02-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter_downloader", "0020_alter_broadcastlog_error_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="forward_channel_id",
            field=models.CharField(
                blank=True, help_text="Telegram channel ID (e.g. @channelname or -1001234567890)", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="is_forward_to_channel",
            field=models.BooleanField(
                default=False, help_text="Enable forwarding downloaded tweets to a Telegram channel"
            ),
        ),
    ]
